apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: control-tower-cron
  name: control-tower-cron
  namespace: gateway
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: control-tower-cron
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: control-tower-cron
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - gateway
      containers:
        - args:
            - startCron
          env:
            - name: PORT
              value: "9000"
            - name: LOGGER_TYPE
              value: console
            - name: NODE_ENV
              value: prod
            - name: NODE_PATH
              value: app/src
            - name: PUBLIC_URL
              value: http://production-api.globalforestwatch.org
            - name: AUTHORIZATION_URL
              value: http://authorization.core.svc.cluster.local:9000
            - name: APP_NAME
              value: RW API
            - name: APP_LOGO
              value: http://www.wri.org/sites/all/themes/wri/images/logo.png
            - name: APP_COLOR
              value: '#f1b319'
            - name: CT_MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: CT_MONGO_URI
                  name: control-tower
            - name: SESSION_KEY
              valueFrom:
                secretKeyRef:
                  key: SESSION_KEY
                  name: control-tower
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: control-tower
            - name: FASTLY_ENABLED
              valueFrom:
                secretKeyRef:
                  key: FASTLY_ENABLED
                  name: mssecrets
            - name: FASTLY_APIKEY
              valueFrom:
                secretKeyRef:
                  key: FASTLY_APIKEY
                  name: mssecrets
                  optional: true
            - name: FASTLY_SERVICEID
              valueFrom:
                secretKeyRef:
                  key: FASTLY_SERVICEID
                  name: mssecrets
                  optional: true
          image: gfwdockerhub/control-tower
          imagePullPolicy: Always
          name: control-tower-cron
          resources:
            limits:
              cpu: "1"
              memory: 512M
            requests:
              cpu: 350m
              memory: 256M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
