version: "3"
services:
  test:
    build: .
    ports:
      - "9000:9000"
    container_name: control-tower-test
    environment:
      NODE_ENV: test
      SESSION_KEY: test
      PORT: 9000
      LOGGER_TYPE: console
      DEBUG: redis-cache-plugin
      NODE_PATH: app/src
      JWT_SECRET: mysecret
      COOKIE_DOMAIN: mymachine
      PUBLIC_URL: http://localhost:9000
      MONGO_PORT_27017_TCP_ADDR: mongo
      FASTLY_APIKEY: foo
      FASTLY_SERVICEID: bar
      CT_URL: http://control-tower.gateway.svc.cluster.local:9000
    command: test
    depends_on:
      - mongo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:3.6.13
    command: --smallfiles
    ports:
      - "27017"
