version: "3"
services:
  develop:
    build: .
    ports:
      - "9000:9000"
    container_name: control-tower
    env_file:
      - dev.env
    command: develop
    depends_on:
      - mongo
    volumes:
      #      - ./app:/opt/control-tower/app
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:3.6.13
    container_name: control-tower-mongo
    ports:
      - "27017:27017"
    volumes:
      - $HOME/docker/control-tower/mongodb:/data/db
    restart: always
